### ISSUE TITLE
安卓推送问题

### ISSUE THREAD

**Issue by zsk2017** [wildfirechat/push_server#1]
server端配置了推送服务的相关配置，推送服务端修改了小米的key，但是所有的安卓推送并没有成功执行推送服务端的安卓推送接口，小米平台也没有任何消息记录，请问作者这是什么原因导致的

**Comment by 871846173** [comment]
你好，您的这个问题解决了吗，我也是安卓的，自己写了一个业务用这个推送，结果安卓收不到ios可以收到，不知道怎么回事

**Comment by heavyrain2012** [comment]
更新到最新的服务试试，如果能到推送服务之后的就需要你们自己来调了
