### ISSUE TITLE
建议支持google海外推送标准firebase推送

### ISSUE THREAD

**Issue by zuoliang0** [wildfirechat/push_server#15]
建议demo中支持google的海外推送，这个不仅需要前端采集firebase的token还需要后台支持，但是这个推送是海外推送的真正的标准。前身是GCM推送，建议官方集成

**Comment by mankind-evolve** [comment]
支持。很需要

**Comment by heavyrain2012** [comment]
这个你们自己来对接就可以了，客户端加上注册谷歌推送代码，获取到token后把token和类型（自己定义一个新的就行）传入setDeviceToken函数，这样当服务器判断需要推送时就会把所有信息（包括token和类型）都发送到推送服务，推送服务根据类型来调用对应的sdk来推送就好了

**Comment by zuoliang0** [comment]
> 这个你们自己来对接就可以了，客户端加上注册谷歌推送代码，获取到token后把token和类型（自己定义一个新的就行）传入setDeviceToken函数，这样当服务器判断需要推送时就会把所有信息（包括token和类型）都发送到推送服务，推送服务根据类型来调用对应的sdk来推送就好了

是的，我们确实也是这样做的。不过fcm作为事实标准可以考虑接入。谢谢

**Comment by mankind-evolve** [comment]
@zuoliang0 老哥。你接入了吗？ 可以分享一下吗？ 有偿！ 技术有限。搞不大定

**Comment by heavyrain2012** [comment]
我们准备加上，预计一周左右吧

**Comment by heavyrain2012** [comment]
已提交，请更新android客户端和push server验证

**Comment by mankind-evolve** [comment]
十分十分感谢
