### ISSUE TITLE
IOS推送问题

### ISSUE THREAD

**Issue by 871846173** [wildfirechat/push_server#2]
在推送apns 添加了ios的两个证书，然后改了
apns.product_cer_path=apns/app_push.p12//开发模式
apns.product_cer_pwd=123456
apns.develop_cer_path=apns/dev_push.p12  //生产模式
apns.develop_cer_pwd=123456
apns.voip_cer_path=apns/wildfirechat_voip_push.p12
apns.voip_cer_pwd=123456

可是还是没办法推送，照着文档改了还是没办法推送，还需要改其他什么地方的文件吗？

**Comment by heavyrain2012** [comment]
需要进行debug，可以先看一下苹果返回来的错误码
