### ISSUE TITLE
推送收不到信息，请求判断一下哪里出了问题

### ISSUE THREAD

**Issue by mankind-evolve** [wildfirechat/push_server#31]
一直收不到

访问推送地址出现一个错误

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Sep 15 17:56:59 CST 2022
There was an unexpected error (type=Method Not Allowed, status=405).
Request method 'GET' not supported

**Comment by mankind-evolve** [comment]
0.1.2版本

**Comment by heavyrain2012** [comment]
访问推送地址 是什么意思，是IM服务调用推送服务吗？还是浏览器里输入推送服务地址？

**Comment by heavyrain2012** [comment]
推送服务代码还是很简单的，就是收到IM服务过来的推送请求，然后调用推送厂商的推送，你们可以看一下代码再debug一下
