### ISSUE TITLE
频道发送信息问题

### ISSUE THREAD

**Issue by xushuai21** [wildfirechat/push_server#32]
# 关于手机锁屏，频道发来信息显示用户信息问题

当用户手机锁屏，频道发来信息，手机上的提醒显示的是用户信息 而不是频道信息

**Comment by heavyrain2012** [comment]
检查一下是不是远程推送，如果远程推送我们应该已经改了，请检查推送服务的提交 https://github.com/wildfirechat/push_server/commit/af56062f6295a99cd9c65480165e1cbd38c62f29
