### ISSUE TITLE
小米的这个错误，  com.xiaomi.push.sdk.ErrorCode@2c5c63ff

### ISSUE THREAD

**Issue by huazaihuola** [wildfirechat/push_server#35]
Server response: MessageId: Xdm68171686069405872Cm ErrorCode: com.xiaomi.push.sdk.ErrorCode@2c5c63ff Reason: AppId(id=2882303761520086841) in the blacklist, forbid to send messages

这个错误：com.xiaomi.push.sdk.ErrorCode@2c5c63ff
打印的是队形的内存地址，不是具体信息：

![image](https://github.com/wildfirechat/push_server/assets/49841444/95fe5248-4093-47e8-bf64-29b057d8898a)

**Comment by imndx** [comment]
Reason: AppId(id=2882303761520086841) in the blacklist, forbid to send messages
----
看这儿的意思是说：
appId 被加到黑名单了，禁止发消息
