### ISSUE TITLE
ios没办法使用个推

### ISSUE THREAD

**Issue by fightroad** [wildfirechat/push_server#38]
推送服务日志显示接收到了im服务的推送请求，里面的pushtype也是7  但是ios没有办法接收到离线的推送。

**Comment by fightroad** [comment]
unichat只能使用个推。unipush获取到的devicetoken 使用自带的apns推  提示bad divetoken

**Comment by heavyrain2012** [comment]
其实野火关于推送的处理是透传的，只是把所需要的推送数据（消息信息+推送类型+推送token）传出去就完成任务了，剩下的在推送服务和推送厂商了。你需要查询推送厂商的文档或者给他们提工单来处理

**Comment by heavyrain2012** [comment]
> unichat只能使用个推。unipush获取到的devicetoken 使用自带的apns推 提示bad divetoken

这个问题，如果苹果回复bad devicetoken，那就需要检查一下devicetoken从哪里来的，是个推sdk返回的token还是你们自己获取的推送token，如果是个推sdk返回的token那就需要确认一下是不是苹果的token？

**Comment by heavyrain2012** [comment]
> unichat只能使用个推。unipush获取到的devicetoken 使用自带的apns推 提示bad divetoken

如果使用个推，可以把所有的推送全都转到个推去，请改一下代码不使用APNS，改成个推来推送

**Comment by fightroad** [comment]
> > unichat只能使用个推。unipush获取到的devicetoken 使用自带的apns推 提示bad divetoken
> 
> 如果使用个推，可以把所有的推送全都转到个推去，请改一下代码不使用APNS，改成个推来推送

是使用个推  我的意思是安卓的可以使用个推且可以收到通知  但是ios的使用个推没有办法收到。如果推送服务没有抛出异常  是不是代表推送服务已经把消息发个推的接口成功了。

**Comment by fightroad** [comment]
> > > unichat只能使用个推。unipush获取到的devicetoken 使用自带的apns推 提示bad divetoken
> > 
> > 
> > 如果使用个推，可以把所有的推送全都转到个推去，请改一下代码不使用APNS，改成个推来推送
> 
> 是使用个推 我的意思是安卓的可以使用个推且可以收到通知 但是ios的使用个推没有办法收到。如果推送服务没有抛出异常 是不是代表推送服务已经把消息发个推的接口成功了。

个推后台有配置ios推送证书 并且在它后台测试是可以推送离线消息

**Comment by fightroad** [comment]
> > > > unichat只能使用个推。unipush获取到的devicetoken 使用自带的apns推 提示bad divetoken
> > > 
> > > 
> > > 如果使用个推，可以把所有的推送全都转到个推去，请改一下代码不使用APNS，改成个推来推送
> > 
> > 
> > 是使用个推 我的意思是安卓的可以使用个推且可以收到通知 但是ios的使用个推没有办法收到。如果推送服务没有抛出异常 是不是代表推送服务已经把消息发个推的接口成功了。
> 
> 个推后台有配置ios推送证书 并且在它后台测试是可以推送离线消息

应该知道问题出在哪了，是代码里把ios推送个推的ios厂商部分注释掉了。ios是不支持个推通知栏消息的，只能使用厂商通道。但是ios的厂商通道又是没打开的。导致ios接收不到。
![1700707640502](https://github.com/wildfirechat/push_server/assets/39027157/2838d300-dc4d-40ef-8e3b-0fbe24d792ee)

**Comment by fightroad** [comment]
更改推送服务实现
