### ISSUE TITLE
Push API 推送失敗

### ISSUE THREAD

**Issue by ieyoieyo** [wildfirechat/push_server#5]
請問 Push API 的參數/格式是否有範例可以參考？
我依文件嘗試失敗 http://docs.wildfirechat.cn/server/push_config.html
失敗的 Push Server log如下：
`2019-11-19 10:25:41.945  INFO 1664 --- [nio-8085-exec-1] c.w.push.android.xiaomi.XiaomiPush       : Server response: MessageId: Xdm05123574130466226NR ErrorCode: com.xiaomi.push.sdk.ErrorCode@b30939 Reason: No valid targets!`

我指定的「target」是 Samsung廠牌的手機，理論上它會使用「小米推送」沒錯，
我發的 body 如下：
`{"sender":"UhUIUI11","senderName":"1333","convType":0,"target":"VbV8V8hh","targetName":"1222","serverTime":1558350862502,"pushMessageType":0,"pushType":1,"pushContent":"7878787878","unReceivedMsg":0,"deviceToken":"k8uROfAMl7PrVsoXt9i6Idv9UDkQrLoOvkysGKdo/2lE6bdiUZWC9UaVwFHhEkt8zr4sAjqeeSw1vw//aOQKfJF7Qv7Tga+7oak94TZxKsyFPz7EZO6Yxu/7vxRTc8ff/u5SDJx6+vSrRd+ArlUpuanvLyYgCqmGYY0wtJcOU9M="}`

**Comment by heavyrain2012** [comment]
推送服务需要开发者自己来调试
